# this runs everything as root
- name: Setup an Ubuntu 24.04 Minecraft server
  hosts: all:!localhost
  gather_facts: true
  become: true
  tasks:

    - name: "apt: update and upgrade packages"
      become: true
      apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 86400

    - name: "apt: install needed packages"
      ansible.builtin.package:
        name:
          - htop
          - vim
          - fish
          - sshpass
        state: latest

    - name: "Setup Minecraft user"
      ansible.builtin.user:
        name: minecraft
        groups: sudo
        append: true
        create_home: true
        shell: "/usr/bin/fish"
        # TODO
        password: "$1$salt-Lwv$9XUBHYDTTUyoIpsezekG7/"

    - name: "Add SSH authorized key to user"
      ansible.posix.authorized_key:
        user: minecraft
        state: present
        key: "{{ lookup('file', '~/.ssh/id_ed25519_adhoc-mc.pub') }}"

    - name: "Harden SSH: change port"
      ansible.builtin.lineinfile:
        dest: /etc/ssh/sshd_config
        regexp: "^#Port"
        line: "Port 9889"

    - name: "Harden SSH: disable password authentication"
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: "^#PasswordAuthentication yes"
        line: "PasswordAuthentication no"

    - name: "Harden SSH: disable root login"
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: "^#PermitRootLogin"
        line: "PermitRootLogin no"

    - name: "Restart SSH daemon"
      ansible.builtin.command: "systemctl restart ssh"

    - name: "Install Docker"
      include_role:
        name: geerlingguy.docker # installs docker

    - name: "Add minecraft user to docker group"
      ansible.builtin.user:
        name: minecraft
        groups: docker
        append: true

    - name: "Run Docker Container itzg/docker-minecraft-server"
      become_user: minecraft
      ansible.builtin.command: >
        docker run --detach
        --name minecraft
        --publish 25565:25565
        --volume /home/minecraft/data:/data
        -e EULA=TRUE
        -e MEMORY=7G
        -e MOTD="minecraft server"
        -e DIFFICULTY=normal
        itzg/minecraft-server

